# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_political_nickname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome Eleitoral do Candidato')),
                ('candidate_dispute_party', models.CharField(blank=True, choices=[('pmdb', 'PMDB'), ('pt', 'PT'), ('psdb', 'PSDB'), ('pp', 'PP'), ('pdt', 'PDT'), ('dem', 'DEMOCRATAS'), ('pr', 'PR'), ('psb', 'PSB'), ('pps', 'PPS'), ('pcdob', 'PCdoB'), ('prb', 'PRB'), ('pv', 'PV'), ('psd', 'PSD'), ('prp', 'PRP'), ('psl', 'PSL'), ('pmn', 'PMN'), ('phs', 'PHS'), ('ptc', 'PTC'), ('sd', 'SOLIDARIEDADE'), ('psdC', 'PSDC'), ('avante', 'AVANTE'), ('podemos', 'PODE'), ('psol', 'PSOL')], max_length=50, null=True)),
                ('canditate_Election_Ballot', models.CharField(blank=True, choices=[('2018', 'Eleições 2018'), ('2020', 'Eleições 2020')], max_length=30, null=True, verbose_name='Pleito de Disputa Eleitoral')),
                ('campaign_desired_position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo de Disputa')),
                ('state_campaign', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF de Campanha')),
                ('city_campaign', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade de Campanha')),
                ('candidate_dispute_number', models.CharField(blank=True, max_length=6, null=True, verbose_name='Número do Candidato')),
                ('slug', models.SlugField(blank=True, verbose_name='Atalho')),
                ('holds_political_position', models.BooleanField(default='False', verbose_name='Detém Cargo Político')),
                ('political_position', models.CharField(blank=True, max_length=40, null=True, verbose_name='Posição Politica que Exerce')),
                ('reelection', models.BooleanField(default='False', verbose_name='Tentando Reeleição')),
                ('first_political_campaign', models.BooleanField(default='False', verbose_name='Detém Cargo Político')),
                ('candidate_site', models.CharField(blank=True, max_length=50, null=True, verbose_name='Site do Candidate')),
                ('campaign_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Candidato')),
                ('facebook', models.CharField(blank=True, max_length=40, null=True)),
                ('twitter', models.CharField(blank=True, max_length=40, null=True)),
                ('google', models.CharField(blank=True, max_length=40, null=True)),
                ('youtube', models.CharField(blank=True, max_length=40, null=True)),
                ('instagram', models.CharField(blank=True, max_length=40, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/Candidatos', verbose_name='FotoCandidato')),
                ('Resume', models.TextField(blank=True, null=True, verbose_name='Currículo')),
                ('Obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('candidate_situation', models.CharField(choices=[('aproved', 'Aprovado'), ('denied ', 'Não Aprovado'), ('pending', 'Aguardando Aprovação')], default='pending', max_length=40, verbose_name='Situation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
