# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 21:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_political_nickname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome Eleitoral do Candidato')),
                ('candidate_dispute_party', models.CharField(blank=True, choices=[('pmdb', 'PMDB'), ('pt', 'PT'), ('psdb', 'PSDB'), ('pp', 'PP'), ('pdt', 'PDT'), ('dem', 'DEMOCRATAS'), ('pr', 'PR'), ('psb', 'PSB'), ('pps', 'PPS'), ('pcdob', 'PCdoB'), ('prb', 'PRB'), ('pv', 'PV'), ('psd', 'PSD'), ('prp', 'PRP'), ('psl', 'PSL'), ('pmn', 'PMN'), ('phs', 'PHS'), ('ptc', 'PTC'), ('sd', 'SOLIDARIEDADE'), ('psdC', 'PSDC'), ('avante', 'AVANTE'), ('podemos', 'PODE'), ('psol', 'PSOL')], max_length=50, null=True)),
                ('canditate_Election_Ballot', models.CharField(blank=True, choices=[('2018', 'Eleições 2018'), ('2020', 'Eleições 2020')], max_length=30, null=True, verbose_name='Pleito de Disputa Eleitoral')),
                ('campaign_desired_position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo de Disputa')),
                ('state_campaign', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF de Campanha')),
                ('city_campaign', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade de Campanha')),
                ('candidate_dispute_number', models.CharField(blank=True, max_length=6, null=True, verbose_name='Número do Candidato')),
                ('slug', models.SlugField(blank=True, verbose_name='Atalho')),
                ('holds_political_position', models.BooleanField(default='False', verbose_name='Detém Cargo Político')),
                ('political_position', models.CharField(blank=True, max_length=40, null=True, verbose_name='Posição Politica que Exerce')),
                ('reelection', models.BooleanField(default='False', verbose_name='Tentando Reeleição')),
                ('first_political_campaign', models.BooleanField(default='False', verbose_name='Detém Cargo Político')),
                ('candidate_site', models.CharField(blank=True, max_length=50, null=True, verbose_name='Site do Candidate')),
                ('campaign_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Candidato')),
                ('facebook', models.CharField(blank=True, max_length=40, null=True)),
                ('twitter', models.CharField(blank=True, max_length=40, null=True)),
                ('google', models.CharField(blank=True, max_length=40, null=True)),
                ('youtube', models.CharField(blank=True, max_length=40, null=True)),
                ('instagram', models.CharField(blank=True, max_length=40, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/Candidatos', verbose_name='FotoCandidato')),
                ('Resume', models.TextField(blank=True, null=True, verbose_name='Currículo')),
                ('Obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('candidate_situation', models.CharField(choices=[('aproved', 'Aprovado'), ('denied ', 'Não Aprovado'), ('pending', 'Aguardando Aprovação')], default='pending', max_length=40, verbose_name='Situation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Coalitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_coligation', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome Coligação')),
                ('political_partie_abbreviation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla Partirária')),
            ],
        ),
        migrations.CreateModel(
            name='Committee_Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Atribuições')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
        migrations.CreateModel(
            name='Committees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cellPhone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('landlinePhone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone Fixo')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='Geral', max_length=40, verbose_name='Regras das Funções')),
                ('budget_managment', models.PositiveSmallIntegerField(default=0, verbose_name='Controle Financeiro')),
                ('members_managment', models.PositiveSmallIntegerField(default=4, verbose_name='Gestão de Usuários')),
                ('reports_managment', models.PositiveSmallIntegerField(default=2, verbose_name='Gestão de Relatórios')),
                ('members_access', models.PositiveSmallIntegerField(default=4, verbose_name='Acesso a Membros')),
                ('agenda_access', models.PositiveSmallIntegerField(default=6, verbose_name='Acesso à Agenda')),
                ('internetInteraction', models.PositiveSmallIntegerField(default=7, verbose_name='interação com outros membros')),
                ('sendMessages', models.PositiveSmallIntegerField(default=6, verbose_name='Enviar Mensagens')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=40, verbose_name='Função do Usuário')),
                ('budget_managment', models.PositiveSmallIntegerField(default=0, verbose_name='Controle Financeiro')),
                ('members_managment', models.PositiveSmallIntegerField(default=4, verbose_name='Gestão de Usuários')),
                ('reports_managment', models.PositiveSmallIntegerField(default=2, verbose_name='Gestão de Relatórios')),
                ('members_access', models.PositiveSmallIntegerField(default=4, verbose_name='Acesso a Membros')),
                ('agenda_access', models.PositiveSmallIntegerField(default=6, verbose_name='Acesso à Agenda')),
                ('internetInteraction', models.PositiveSmallIntegerField(default=7, verbose_name='interação com outros membros')),
                ('sendMessages', models.PositiveSmallIntegerField(default=6, verbose_name='Enviar Mensagens')),
            ],
        ),
    ]
