# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-23 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180322_0055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='usuarioes',
            field=models.ManyToManyField(blank=True, to='dashboard.Usuario'),
        ),
    ]
