# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-12 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180404_1219'),
        ('candidato', '0002_auto_20180323_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_in_user_roles', to='candidato.Candidate'),
        ),
        migrations.AddField(
            model_name='userroles',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_in_user_roles', to='dashboard.Usuario'),
        ),
    ]
