# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_coalitions_committee_members_committees_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='Geral', max_length=40, verbose_name='Regras das Funções')),
                ('budget_managment', models.PositiveSmallIntegerField(default=0, verbose_name='Controle Financeiro')),
                ('members_managment', models.PositiveSmallIntegerField(default=4, verbose_name='Gestão de Usuários')),
                ('reports_managment', models.PositiveSmallIntegerField(default=2, verbose_name='Gestão de Relatórios')),
                ('members_access', models.PositiveSmallIntegerField(default=4, verbose_name='Acesso a Membros')),
                ('agenda_access', models.PositiveSmallIntegerField(default=6, verbose_name='Acesso à Agenda')),
                ('internetInteraction', models.PositiveSmallIntegerField(default=7, verbose_name='interação com outros membros')),
                ('sendMessages', models.PositiveSmallIntegerField(default=6, verbose_name='Enviar Mensagens')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=40, verbose_name='Função do Usuário')),
                ('budget_managment', models.PositiveSmallIntegerField(default=0, verbose_name='Controle Financeiro')),
                ('members_managment', models.PositiveSmallIntegerField(default=4, verbose_name='Gestão de Usuários')),
                ('reports_managment', models.PositiveSmallIntegerField(default=2, verbose_name='Gestão de Relatórios')),
                ('members_access', models.PositiveSmallIntegerField(default=4, verbose_name='Acesso a Membros')),
                ('agenda_access', models.PositiveSmallIntegerField(default=6, verbose_name='Acesso à Agenda')),
                ('internetInteraction', models.PositiveSmallIntegerField(default=7, verbose_name='interação com outros membros')),
                ('sendMessages', models.PositiveSmallIntegerField(default=6, verbose_name='Enviar Mensagens')),
            ],
        ),
        migrations.AddField(
            model_name='committee_members',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
