# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_auto_20180412_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitator_email', models.CharField(max_length=50)),
                ('invited_name', models.CharField(blank=True, max_length=60, null=True)),
                ('invited_email', models.CharField(max_length=60)),
                ('invited_cel', models.CharField(blank=True, max_length=20, null=True)),
                ('candidate_id', models.ManyToManyField(to='candidato.Candidate')),
            ],
        ),
    ]
