# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-20 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0005_merge_20180420_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(blank=True, choices=[('pmdb', 'PMDB'), ('pt', 'PT'), ('psdb', 'PSDB'), ('pp', 'PP'), ('pdt', 'PDT'), ('dem', 'DEMOCRATAS'), ('pr', 'PR'), ('psb', 'PSB'), ('pps', 'PPS'), ('pcdob', 'PCdoB'), ('prb', 'PRB'), ('pv', 'PV'), ('psd', 'PSD'), ('prp', 'PRP'), ('psl', 'PSL'), ('pmn', 'PMN'), ('phs', 'PHS'), ('ptc', 'PTC'), ('sd', 'SOLIDARIEDADE'), ('psdC', 'PSDC'), ('avante', 'AVANTE'), ('podemos', 'PODE'), ('psol', 'PSOL')], max_length=50, null=True),
        ),
    ]
