# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-20 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0006_candidate_candidate_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invites',
            old_name='candidate_id',
            new_name='candidate',
        ),
    ]
