# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0007_auto_20180420_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(blank=True, choices=[('S', 'SUSPENSO'), ('I', 'INATIVO'), ('C', 'CONVIDADO'), ('A', 'ATIVO')], max_length=10, null=True),
        ),
    ]
