# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-26 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0010_candidaterequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidaterequests',
            name='invited_email',
        ),
    ]
