# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-26 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0011_remove_candidaterequests_invited_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterequests',
            name='request_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
