# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-01 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0012_candidaterequests_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_in_user_roles', to='candidato.Invites'),
        ),
    ]
