# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-03 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0013_userroles_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
