# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0015_auto_20180514_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='proposals',
            field=models.ManyToManyField(blank=True, to='candidato.Proposal'),
        ),
    ]
