# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidato', '0016_candidate_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopelist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
