# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0019_auto_20180516_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='negative_keywords',
            field=models.ManyToManyField(blank=True, related_name='n_keyword_in_candidato', to='candidato.Keyword'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='positive_keywords',
            field=models.ManyToManyField(blank=True, related_name='p_keyword_in_candidato', to='candidato.Keyword'),
        ),
    ]
