# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-22 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0020_auto_20180516_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Committee_Members',
            new_name='CommitteeMembers',
        ),
        migrations.RenameModel(
            old_name='UserRoles_list',
            new_name='UserRolesList',
        ),
    ]
