# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-22 09:59
from __future__ import unicode_literals

import core.utils.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180522_0659'),
        ('candidato', '0021_auto_20180522_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True, verbose_name='User Name')),
                ('email', models.TextField(blank=True, null=True, verbose_name='Email')),
                ('kind', models.TextField(blank=True, null=True, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='committees',
            name='cellPhone',
        ),
        migrations.RemoveField(
            model_name='committees',
            name='landlinePhone',
        ),
        migrations.AddField(
            model_name='committeemembers',
            name='commitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidato.Committees'),
        ),
        migrations.AddField(
            model_name='committeemembers',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Usuario'),
        ),
        migrations.AddField(
            model_name='committees',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidato.Candidate'),
        ),
        migrations.AddField(
            model_name='committees',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[core.utils.model_utils.phone_validators]),
        ),
        migrations.AddField(
            model_name='committees',
            name='landline_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[core.utils.model_utils.phone_validators], verbose_name='Telefone Fixo'),
        ),
        migrations.AddField(
            model_name='committees',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='committee_members_in_committee', to='candidato.CommitteeMembers'),
        ),
        migrations.AddField(
            model_name='committees',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Usuario'),
        ),
        migrations.AlterField(
            model_name='committees',
            name='cep',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='committees',
            name='estado',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='committees',
            name='responsible_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidato.TempUser'),
        ),
    ]
