# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0024_auto_20180524_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='Obs',
            new_name='obs',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Resume',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='files/candidatos', verbose_name='Currículo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_election',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Primeira Eleição'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='holds_political_position',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Detém Cargo Político'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='reelection',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tentando Reeleição'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_dispute_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='dashboard.PoliticalParties'),
        ),
    ]
