# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0025_auto_20180529_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_dispute_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.PoliticalParties'),
        ),
    ]
