# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20180615_1324'),
        ('candidato', '0026_auto_20180622_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='campaign_desired_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Position'),
        ),
    ]
