# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-22 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0027_candidate_campaign_desired_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='first_political_campaign',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='holds_political_position',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='holds_position',
        ),
    ]
