# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20180615_1324'),
        ('candidato', '0030_remove_candidate_political_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='political_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_in_political_position', to='elections.Position'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='campaign_desired_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_in_campaign_desired_position', to='elections.Position'),
        ),
    ]
