# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-22 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0032_auto_20180622_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='first_political_campaign',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='reelection',
        ),
    ]
