# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0035_candidate_experience'),
        ('candidato', '0035_auto_20180622_1451'),
    ]

    operations = [
    ]
