# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-26 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0036_merge_20180625_1122'),
        ('candidato', '0036_merge_20180625_1412'),
    ]

    operations = [
    ]
