# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0038_remove_candidate_usuarioes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='intention_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rejection_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
