# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=60, verbose_name='Sobrenome,')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=30, verbose_name='Senha')),
                ('role', models.PositiveSmallIntegerField(verbose_name='Role')),
                ('status', models.PositiveSmallIntegerField(verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('slug', models.SlugField(blank=True, verbose_name='Atalho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
