# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-15 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180522_0659'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=200)),
                ('is_user', models.BooleanField(default=False)),
                ('facebook', models.CharField(blank=True, max_length=40, null=True)),
                ('facebook_img', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, max_length=40, null=True)),
                ('twitter_img', models.TextField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('googlep', models.CharField(blank=True, max_length=40, null=True)),
                ('googlep_img', models.TextField(blank=True, null=True)),
                ('googlep_url', models.URLField(blank=True, null=True)),
                ('youtube', models.CharField(blank=True, max_length=40, null=True)),
                ('youtube_img', models.TextField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=40, null=True)),
                ('instagram_img', models.TextField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('citie', models.ManyToManyField(blank=True, null=True, to='dashboard.Municipio')),
                ('political_party', models.ManyToManyField(to='dashboard.PoliticalParties')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Position')),
                ('state', models.ManyToManyField(blank=True, to='dashboard.Estado')),
            ],
        ),
    ]
