# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-15 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='candidate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='candidato.Candidate'),
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='citie',
        ),
        migrations.AddField(
            model_name='dispute',
            name='citie',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='political_party',
            field=models.ManyToManyField(blank=True, to='dashboard.PoliticalParties'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Position'),
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='state',
        ),
        migrations.AddField(
            model_name='dispute',
            name='state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
