# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-17 21:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=10, unique=True)),
                ('Nome', models.CharField(max_length=255)),
                ('Uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('CodigoUf', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nome', models.CharField(max_length=50)),
                ('Uf', models.CharField(max_length=2)),
                ('Regiao', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField(unique=True)),
                ('Nome', models.CharField(max_length=255)),
                ('Uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=6, verbose_name='Sigla')),
                ('name', models.CharField(max_length=70, verbose_name='Nome do Partido')),
                ('electoral_number', models.CharField(max_length=3, verbose_name='Número Eleitoral')),
                ('affiliates_number', models.IntegerField(verbose_name='Número de Filiados')),
                ('president_name', models.CharField(max_length=60, verbose_name='Presidente Atual')),
                ('political_spectrum', models.CharField(blank=True, choices=[('Centro', 'Centro'), ('CentroDireita', 'Centro Direita'), ('CentroEsquerda', 'Centro Esquerda'), ('Esquerda', 'Esquerda'), ('ExtremaDireita', 'Extrema Direita'), ('ExtremaEsquerda', 'Extrema Esquerda')], max_length=100, null=True)),
                ('image_flag', models.ImageField(blank=True, null=True, upload_to='images/political_flags', verbose_name='bandeiraPartido')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Gênero')),
                ('marital_status', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Estado Civil')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cellPhone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('landlinePhone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone Fixo')),
                ('email_verified', models.NullBooleanField()),
                ('user_political_party', models.CharField(blank=True, choices=[('pmdb', 'PMDB'), ('pt', 'PT'), ('psdb', 'PSDB'), ('pp', 'PP'), ('pdt', 'PDT'), ('dem', 'DEMOCRATAS'), ('pr', 'PR'), ('psb', 'PSB'), ('pps', 'PPS'), ('pcdob', 'PCdoB'), ('prb', 'PRB'), ('pv', 'PV'), ('psd', 'PSD'), ('prp', 'PRP'), ('psl', 'PSL'), ('pmn', 'PMN'), ('phs', 'PHS'), ('ptc', 'PTC'), ('sd', 'SOLIDARIEDADE'), ('psdC', 'PSDC'), ('avante', 'AVANTE'), ('podemos', 'PODE'), ('psol', 'PSOL')], max_length=50, null=True)),
                ('user_profile_photo', models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='foto')),
                ('created_date', models.DateField(auto_now=True, null=True)),
                ('id_candidate', models.IntegerField(blank=True, null=True, verbose_name='Id candidato')),
                ('candidate_political_party', models.CharField(blank=True, choices=[('pmdb', 'PMDB'), ('pt', 'PT'), ('psdb', 'PSDB'), ('pp', 'PP'), ('pdt', 'PDT'), ('dem', 'DEMOCRATAS'), ('pr', 'PR'), ('psb', 'PSB'), ('pps', 'PPS'), ('pcdob', 'PCdoB'), ('prb', 'PRB'), ('pv', 'PV'), ('psd', 'PSD'), ('prp', 'PRP'), ('psl', 'PSL'), ('pmn', 'PMN'), ('phs', 'PHS'), ('ptc', 'PTC'), ('sd', 'SOLIDARIEDADE'), ('psdC', 'PSDC'), ('avante', 'AVANTE'), ('podemos', 'PODE'), ('psol', 'PSOL')], max_length=50, null=True)),
                ('candidate_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Candidato')),
                ('candidate_estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do Candidato')),
                ('candidate_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade do Candidato')),
                ('candidate_email', models.EmailField(max_length=254, null=True, verbose_name='Email do Candidato')),
                ('user_status', models.CharField(choices=[('aproved', 'Aprovado'), ('denied ', 'Não Aprovado'), ('pending', 'Aguardando Aprovação')], max_length=40, verbose_name='Status')),
                ('user_role', models.CharField(choices=[('subscriber', 'Assinante'), ('agency', 'Agência de Marketing'), ('consultor', 'Consultor de Campanha'), ('external_contractor', 'Contratado Externo'), ('internal_employee', 'Empregado Interno'), ('outsourced', 'Terceirizado'), ('voluntary', 'Voluntário')], max_length=40, verbose_name='Tipo de Acesso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
