# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 22:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Codigo', models.CharField(max_length=10, unique=True)),
                ('Nome', models.CharField(max_length=255)),
                ('Uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Numero Partido')),
                ('CodigoUf', models.PositiveSmallIntegerField(unique=True)),
                ('Nome', models.CharField(max_length=50)),
                ('Uf', models.CharField(max_length=2)),
                ('Regiao', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Codigo', models.IntegerField(unique=True)),
                ('Nome', models.CharField(max_length=255)),
                ('Uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParties',
            fields=[
                ('id_partido', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Numero Partido')),
                ('sigla', models.CharField(max_length=6, verbose_name='Sigla')),
                ('name', models.CharField(max_length=70, verbose_name='Nome do Partido')),
                ('electoral_number', models.CharField(max_length=3, verbose_name='Número Eleitoral')),
                ('affiliates_number', models.IntegerField(verbose_name='Número de Filiados')),
                ('president_name', models.CharField(max_length=60, verbose_name='Presidente Atual')),
                ('political_spectrum', models.CharField(blank=True, choices=[('Centro', 'Centro'), ('CentroDireita', 'Centro Direita'), ('CentroEsquerda', 'Centro Esquerda'), ('Esquerda', 'Esquerda'), ('ExtremaDireita', 'Extrema Direita'), ('ExtremaEsquerda', 'Extrema Esquerda')], max_length=100, null=True)),
                ('image_flag', models.ImageField(blank=True, null=True, upload_to='images/political_flags', verbose_name='bandeiraPartido')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('political_party', models.CharField(blank=True, choices=[('decratic', 'Democratic'), ('republic', 'Republic'), ('beer', 'Beer')], max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_date', models.DateField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
