# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParties',
            fields=[
                ('id_partido', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Numero Partido')),
                ('sigla', models.CharField(max_length=6, verbose_name='Sigla')),
                ('name', models.CharField(max_length=70, verbose_name='Nome do Partido')),
                ('electoral_number', models.CharField(max_length=3, verbose_name='Número Eleitoral')),
                ('affiliates_number', models.IntegerField(verbose_name='Número de Filiados')),
                ('president_name', models.CharField(max_length=60, verbose_name='Presidente Atual')),
                ('political_spectrum', models.CharField(blank=True, choices=[('Centro', 'Centro'), ('CentroDireita', 'Centro Direita'), ('CentroEsquerda', 'Centro Esquerda'), ('Esquerda', 'Esquerda'), ('ExtremaDireita', 'Extrema Direita'), ('ExtremaEsquerda', 'Extrema Esquerda')], max_length=100, null=True)),
                ('image_flag', models.ImageField(blank=True, null=True, upload_to='images/political_flags', verbose_name='bandeiraPartido')),
            ],
        ),
    ]
