# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='id',
        ),
        migrations.AlterField(
            model_name='estado',
            name='CodigoUf',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
