# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180319_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship_network',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
