# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_politicalparties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Codigo', models.CharField(max_length=10, unique=True)),
                ('Nome', models.CharField(max_length=255)),
                ('Uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('CodigoUf', models.PositiveSmallIntegerField(unique=True)),
                ('Nome', models.CharField(max_length=50)),
                ('Uf', models.CharField(max_length=2, unique=True)),
                ('Regiao', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Codigo', models.IntegerField(unique=True)),
                ('Nome', models.CharField(max_length=255)),
                ('Uf', models.CharField(max_length=2)),
            ],
        ),
    ]
