# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180315_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='cellPhone',
        ),
        migrations.RemoveField(
            model_name='bairro',
            name='Id',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='Id',
        ),
        migrations.RemoveField(
            model_name='politicalparties',
            name='id_partido',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='political_party',
        ),
        migrations.AddField(
            model_name='bairro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicalparties',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='candidate_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade do Candidato'),
        ),
        migrations.AddField(
            model_name='profile',
            name='candidate_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email do Candidato'),
        ),
        migrations.AddField(
            model_name='profile',
            name='candidate_estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do Candidato'),
        ),
        migrations.AddField(
            model_name='profile',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Candidato'),
        ),
        migrations.AddField(
            model_name='profile',
            name='candidate_political_party',
            field=models.CharField(blank=True, choices=[('pmdb', 'PMDB'), ('pt', 'PT'), ('psdb', 'PSDB'), ('pp', 'PP'), ('pdt', 'PDT'), ('dem', 'DEMOCRATAS'), ('pr', 'PR'), ('psb', 'PSB'), ('pps', 'PPS'), ('pcdob', 'PCdoB'), ('prb', 'PRB'), ('pv', 'PV'), ('psd', 'PSD'), ('prp', 'PRP'), ('psl', 'PSL'), ('pmn', 'PMN'), ('phs', 'PHS'), ('ptc', 'PTC'), ('sd', 'SOLIDARIEDADE'), ('psdC', 'PSDC'), ('avante', 'AVANTE'), ('podemos', 'PODE'), ('psol', 'PSOL')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_candidate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id candidato'),
        ),
        migrations.AddField(
            model_name='profile',
            name='landlinePhone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_political_party',
            field=models.CharField(blank=True, choices=[('pmdb', 'PMDB'), ('pt', 'PT'), ('psdb', 'PSDB'), ('pp', 'PP'), ('pdt', 'PDT'), ('dem', 'DEMOCRATAS'), ('pr', 'PR'), ('psb', 'PSB'), ('pps', 'PPS'), ('pcdob', 'PCdoB'), ('prb', 'PRB'), ('pv', 'PV'), ('psd', 'PSD'), ('prp', 'PRP'), ('psl', 'PSL'), ('pmn', 'PMN'), ('phs', 'PHS'), ('ptc', 'PTC'), ('sd', 'SOLIDARIEDADE'), ('psdC', 'PSDC'), ('avante', 'AVANTE'), ('podemos', 'PODE'), ('psol', 'PSOL')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('subscriber', 'Assinante'), ('agency', 'Agência de Marketing'), ('consultor', 'Consultor de Campanha'), ('external_contractor', 'Contratado Externo'), ('internal_employee', 'Empregado Interno'), ('outsourced', 'Terceirizado'), ('voluntary', 'Voluntário')], default='assinante', max_length=40, verbose_name='Tipo de Acesso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_status',
            field=models.CharField(choices=[('aproved', 'Aprovado'), ('denied ', 'Não Aprovado'), ('pending', 'Aguardando Aprovação')], default='pending', max_length=40, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
