# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-20 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180419_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='birthday_date',
            field=models.TextField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
