# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-09 15:59
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180508_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cellPhone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[dashboard.models.phone_validators]),
        ),
    ]
