# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-22 09:59
from __future__ import unicode_literals

import core.utils.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180509_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='relationship_network',
            new_name='RelationshipNetwork',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cellPhone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='landlinePhone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[core.utils.model_utils.phone_validators], verbose_name='Telefone Fixo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_roles_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles_list_in_usuario', to='candidato.UserRolesList'),
        ),
    ]
